<?php return array(
    "INCLUDE_JQUERY_DATATABLES" => true,
    "INCLUDE_JQUERY_AUTOCOMPLETE" => true,
    "INCLUDE_JQUERY_AUTORESIZE" => true,
    "INCLUDE_JQUERY_FORM" => true,
    "INCLUDE_LESS_CSS" => true,
    "INCLUDE_TWITTER_BOOTSTRAP" => true,
    "INCLUDE_TWITTER_BOOTSTRAP_BOOTBOX" => true,
    "INCLUDE_TWITTER_BOOTSTRAP_IMAGEGALLERY" => false,
    "TWITTER_BOOTSTRAP_RESPONSIVE_CSS" => false,
);