<?php namespace nanomvc; ?>
<?php $this->layout->enterSection("head"); ?>
<title><?php echo $this->topic; ?></title>
<?php $this->layout->exitSection(); ?>
<h1><?php echo $this->topic; ?></h1>
<?php echo $this->body; ?>
<p><small><?php echo "Generated by nanoMVC/" . VERSION . " " . date("r"); ?></small></p>